### ISSUE TITLE
Debian build failures

### ISSUE THREAD

**Issue by firefart** [pin/tftp#87]
It looks like some of the tests are currently failing on the debian build infrastructure:
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1036256

@pin maybe you could have a look if you can reproduce them?

The traces maybe hint to one of the time.sleep calls which might add up

**Comment by elboulangero** [comment]
Let me be a bit more specific. I just updated the package in Debian to latest version (`3.0.0`). Then I ran the unit tests for all architectures, 2 times (page is https://ci.debian.net/packages/g/golang-github-pin-tftp/). We have 8 architectures in Debian CI, so it means that the tests ran 16 times.

The test `TestHookSuccess` failed twice, as can be seen at:
* https://ci.debian.net/data/autopkgtest/unstable/riscv64/g/golang-github-pin-tftp/38038625/log.gz
* https://ci.debian.net/data/autopkgtest/unstable/ppc64el/g/golang-github-pin-tftp/38044604/log.gz

Failure is:

```
591s === RUN   TestHookSuccess
591s     tftp_test.go:201: unexpected completed transfers count: 0
591s --- FAIL: TestHookSuccess (0.00s)
```

Note that the 2 failures where on different architectures, meaning that it's not really a hard failure that is architecture specific, but it seems more like the test is flaky.

From the top of your head, do you see any reason why the test `TestHookSuccess` would be flaky? The test command is `go test -vet=off -v -p 4 github.com/pin/tftp github.com/pin/tftp/netascii`, do you think it could be due to `-p 4`?

Thanks!

**Comment by pin** [comment]
Thank you for the report and for detailed repro steps. I was able to repro on amd64 using

```
time while true; do go test -vet=off -v -run TestHookSuccess || break; done
```

Takes only a few seconds on my computer :)

It is indeed a race. #92 is potential fix, going to sleep on it and let anyone opportunity to review and complain.

**Comment by elboulangero** [comment]
> let anyone opportunity to review and complain

I definitely won't complain :D Happy to see that it was easy to reproduce, and apparently easy to fix.

I didn't even know how to run a particular test so far, thanks for sharing this one-liner, I'll re-use it for sure.

**Comment by firefart** [comment]
Looks good for me thanks!

**Comment by pin** [comment]
Just added `v.3.1.0` release that includes #92
